---
- hosts: localhost
  connection: local
  become: true
  tasks: 

  - name: update all packages
    ansible.builtin.apt:
    update: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

  - name: install_apache2
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribition == "Ubuntu"
